honcheonui/main/urls.py
from django.conf.urls.defaults import *

from django.views.generic.list_detail import object_list
from django.views.generic.create_update import create_object

from main.models import ServiceInstance,ServiceItem

urlpatterns = patterns('',
	(r'^services/$', object_list,
		{'queryset':ServiceInstance.objects.all(),}),
	(r'^serviceitems/$', object_list,
		{'queryset':ServiceItem.objects.all(),}),
)

honcheonui/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^/*', include('main.urls')),
	(r'^universe/', include('universe.urls')),
	(r'^kyeong/', include('kyeong.urls')),
	(r'^admin/', include(admin.site.urls)),
)

honcheonui/main/models.py
from django.db import models
from django.contrib.auth.models import User

from universe.models import Volume

# Create your models here.

TYPE_SEL = (
	('M', 'Virtual Machine'),
	('S', 'Storage'),
)

SOURCE_SEL = (
	('S', 'Standard'),
	('T', 'Third Party'),
	('B', 'Backup'),
	('C', 'Custom'),
)

RELEASE_STATUS_SEL = (
	('D', 'Draft'),
	('R', 'Released'),
	('P', 'Postponed'),
	('E', 'Expired'),
)

STATUS_SEL = (
	('N', 'New'),
	('A', 'Active'),
	('R', 'Running'),
	('S', 'Suspended'),
	('E', 'Expired'),
)


class ServiceItem(models.Model):
	name = models.CharField(max_length=80)
	type = models.CharField(max_length=1, choices=TYPE_SEL)
	description = models.CharField(max_length=256,null=True,blank=True)

	status = models.CharField(max_length=1,
			default='D', choices=RELEASE_STATUS_SEL)
	source = models.CharField(max_length=1,default='S',choices=SOURCE_SEL)

	owner = models.ForeignKey(User)

	template = models.ForeignKey(Volume,null=True,blank=True)
	num_spare = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class ServiceInstance(models.Model):
	name = models.CharField(max_length=80)
	status = models.CharField(max_length=1,default='N',choices=STATUS_SEL)
	point_used = models.IntegerField()
	point_plan = models.IntegerField()

	item = models.ForeignKey(ServiceItem)
	user = models.ForeignKey(User)

	cpus = models.IntegerField()
	memory = models.IntegerField()
	storage = models.IntegerField()

	def __unicode__(self):
		return self.name

	def available_templates(self):
		return Volume.objects.filter(is_template=True)

honcheonui/main/templates/main/serviceinstance_list.html
{% extends "base.html" %}

{% block title %}Service Instance{% endblock %}

{% block style %}{% endblock %}

{% block content %}


<div class="wgt_ds">
	<h2>My Services</h2>
	<div class="action" id="service_action">
		<a href="create/">(Create Service)</a>
		<a href="/serviceitems/">New Service</a>
	</div>
	<table class="sheet" id="service_list">
		<tr>
			<th>id</th>
			<th>name</th>
			<th>status</th>
			<th>usage</th>
			<th>service</th>
			<th>type</th>
			<th>user</th>
			<th>cpus</th>
			<th>memory</th>
			<th>storage</th>
			<th>action</th>
		</tr>
		{% for svc in object_list %}
		<tr>
			<td class="tac">{{ svc.id }}</td>
			<td>{{ svc.name }}</td>
			<td class="tac">{{ svc.get_status_display }}</td>
			<td class="tar">{{ svc.point_used }} /
			{{ svc.point_plan }}</td>
			<td class="tac">{{ svc.item.name }}</td>
			<td class="tac">{{ svc.item.get_type_display }}</td>
			<td class="tac">{{ svc.user.username }}</td>
			<td class="tar">{{ svc.cpus }}</td>
			<td class="tar">{{ svc.memory }}</td>
			<td class="tar">{{ svc.storage }}</td>
			<td class="tac">S T P C</td>
		</tr>
		{% endfor %}
	</table>
</div>

{% endblock %}

honcheonui/main/templates/main/serviceitem_list.html
{% extends "base.html" %}

{% block title %}Service Instance{% endblock %}

{% block style %}{% endblock %}

{% block content %}


<div class="wgt_ds">
	<h2>Service Items</h2>
	<div class="action" id="service_action">
		<a href="create/">New Service</a>
	</div>
	<table class="sheet" id="service_list">
		<tr>
			<th>id</th>
			<th>name</th>
			<th>type</th>
			<th>owner</th>
			<th>template</th>
			<th>type (pool / volume)</th>
			<th>source</th>
			<th>action</th>
		</tr>
		{% for item in object_list %}
		<tr>
			<td class="tac">{{ item.id }}</td>
			<td>{{ item.name }}</td>
			<td>{{ item.get_type_display }}</td>
			<td>{{ item.owner.username }}</td>
			<td>{{ item.template }}</td>
			<td>{{ item.template.get_type_display }}
			({{ item.template.pool }})
			</td>
			<td>{{ item.template.get_source_display }}</td>
			<td><a href="services/create/">make instance</a></td>
		</tr>
		{% endfor %}
	</table>
</div>

<!--
{% load universe_tags %}
{% template_list %}
-->

{% endblock %}