honcheonui/universe/urls.py
from django.conf.urls.defaults import *

from django.views.generic.list_detail import object_list
from django.views.generic.create_update import create_object

from universe.models import *

urlpatterns = patterns('',
	(r'^$', object_list,
		{'queryset':Constellation.objects.all(),}),
	(r'^star/$', 'universe.views.stars'),
	(r'^star/(?P<uuid>.+)/$', 'universe.views.star'),
	(r'^storage/(?P<uuid>.+)/$', 'universe.views.pool'),
)

honcheonui/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^/*', include('main.urls')),
	(r'^universe/', include('universe.urls')),
	(r'^kyeong/', include('kyeong.urls')),
	(r'^admin/', include(admin.site.urls)),
)

honcheonui/main/models.py
from django.db import models
from django.contrib.auth.models import User

from universe.models import Volume

# Create your models here.

TYPE_SEL = (
	('M', 'Virtual Machine'),
	('S', 'Storage'),
)

SOURCE_SEL = (
	('S', 'Standard'),
	('T', 'Third Party'),
	('B', 'Backup'),
	('C', 'Custom'),
)

RELEASE_STATUS_SEL = (
	('D', 'Draft'),
	('R', 'Released'),
	('P', 'Postponed'),
	('E', 'Expired'),
)

STATUS_SEL = (
	('N', 'New'),
	('A', 'Active'),
	('R', 'Running'),
	('S', 'Suspended'),
	('E', 'Expired'),
)


class ServiceItem(models.Model):
	name = models.CharField(max_length=80)
	type = models.CharField(max_length=1, choices=TYPE_SEL)
	description = models.CharField(max_length=256,null=True,blank=True)

	status = models.CharField(max_length=1,
			default='D', choices=RELEASE_STATUS_SEL)
	source = models.CharField(max_length=1,default='S',choices=SOURCE_SEL)

	owner = models.ForeignKey(User)

	template = models.ForeignKey(Volume,null=True,blank=True)
	num_spare = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class ServiceInstance(models.Model):
	name = models.CharField(max_length=80)
	status = models.CharField(max_length=1,default='N',choices=STATUS_SEL)
	point_used = models.IntegerField()
	point_plan = models.IntegerField()

	item = models.ForeignKey(ServiceItem)
	user = models.ForeignKey(User)

	cpus = models.IntegerField()
	memory = models.IntegerField()
	storage = models.IntegerField()

	def __unicode__(self):
		return self.name

	def available_templates(self):
		return Volume.objects.filter(is_template=True)

honcheonui/universe/models.py
from django.db import models

import libvirt
import uuid

###
### helper functions

def make_uuid():
	return str(uuid.uuid4())


###
### logical classes

### constellation
class Constellation(models.Model):
	uuid = models.CharField(max_length=36,default=make_uuid,editable=False)
	name = models.CharField(max_length=80)
	location = models.CharField(max_length=128)
	description = models.CharField(max_length=256, null=True,blank=True)

	version = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.name


###
### represent physical part of cluster.

### physical machine
STAR_STATUS_SEL = (
	('r', 'running'),
	('s', 'shutoff'),
)

STAR_MODE_SEL = (
	('c', 'configured'),
	('i', 'installed'),
	('d', 'deployed'),
	('m', 'maintenance'),
)

class Star(models.Model):
	uuid = models.CharField(max_length=36,default=make_uuid,editable=False)
	name = models.CharField(max_length=80)
	uri = models.CharField(max_length=128)

	constellation = models.ForeignKey(Constellation)
	version = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=True)

	## libvirt structure
	hostname = models.CharField(max_length=80,null=True,blank=True)
	type = models.CharField(max_length=20,null=True,blank=True)
	model = models.CharField(max_length=32,null=True,blank=True)
	memory = models.IntegerField(default=0)
	cpus = models.IntegerField(default=0)
	mhz = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class StarStatus(models.Model):
	status = models.CharField(max_length=1, choices=STAR_STATUS_SEL)
	mode = models.CharField(max_length=1, choices=STAR_MODE_SEL)
	class Meta:
		get_latest_by = 'timestamp'


### virtual machine
DOM_STATE_SEL = (
	('0', 'no state'),
	('1', 'running'),
	('2', 'blocked'),
	('3', 'paused'),
	('4', 'shutdown'),
	('5', 'shutoff'),
	('6', 'crashed'),
)

class Light(models.Model):
	uuid = models.CharField(max_length=36)
	name = models.CharField(max_length=80)

	constellation = models.ForeignKey(Constellation)
	version = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=True)

	# is it config or libvirt-info?
	type = models.CharField(max_length=20)
	memory = models.IntegerField(default=0)
	cpus = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class LightStatus(models.Model):
	state = models.CharField(max_length=1,choices=DOM_STATE_SEL)
	cputime = models.PositiveIntegerField(default=0)

	star = models.ForeignKey(Star, null=True, blank=True)

	light = models.ForeignKey(Light)
	timestamp = models.DateTimeField(auto_now=True)
	class Meta:
		get_latest_by = 'timestamp'


### network (virtual or physical)
NETWORK_TYPE_SEL = (
	('I', 'Isolated'),
	('B', 'Bridged'),
	('N', 'NAT'),
)

class Network(models.Model):
	uuid = models.CharField(max_length=36)
	name = models.CharField(max_length=80)
	network = models.CharField(max_length=128,null=True,blank=True)
	dhcp_start = models.IPAddressField(null=True,blank=True)
	dhcp_end =models.IPAddressField(null=True,blank=True)
	type =models.CharField(max_length=1, choices=NETWORK_TYPE_SEL)

	constellation = models.ForeignKey(Constellation)
	version = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=True)

	# is it related on libvirt? global or local?
	bridge = models.CharField(max_length=80)

	def __unicode__(self):
		return self.name


### storage pool
STORAGE_TYPE_SEL = (
	('d', 'directory'),
	('b', 'block device'),
	('i', 'iscsi'),
	('l', 'lvm'),
	('n', 'network fs'),
)

STORAGE_STATE_SEL = (
	('0', 'inactive'),
	('1', 'building'),
	('2', 'running'),
	('3', 'degraded'),
)

class Pool(models.Model):
	uuid = models.CharField(max_length=36)
	name = models.CharField(max_length=80)
	type = models.CharField(max_length=1,default='d',
			choices=STORAGE_TYPE_SEL)
	path = models.CharField(max_length=128,null=True,blank=True)
	is_shared = models.BooleanField(default=False)

	hostname =models.CharField(max_length=128,null=True,blank=True)
	export = models.CharField(max_length=128,null=True,blank=True)

	constellation = models.ForeignKey(Constellation)
	version = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=True)

	capacity = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

class PoolStatus(models.Model):
	state = models.CharField(max_length=1, choices=STORAGE_STATE_SEL)
	allocation = models.IntegerField(default=0)
	available = models.IntegerField(default=0)

	pool = models.ForeignKey(Pool)
	timestamp = models.DateTimeField(auto_now=True)
	class Meta:
		get_latest_by = 'timestamp'

class PoolLink(models.Model):
	pool = models.ForeignKey(Pool)
	star = models.ForeignKey(Star)


### storage volume
VOLUME_TYPE_SEL = (
	('0', 'file'),
	('1', 'block'),
)

class Volume(models.Model):
	uuid = models.CharField(max_length=36)
	name = models.CharField(max_length=80,default='Untitled')
	type = models.CharField(max_length=1,choices=VOLUME_TYPE_SEL)

	# from libvirt?
	path = models.CharField(max_length=265)
	capacity = models.IntegerField(default=0)

	light = models.ForeignKey(Light,null=True,blank=True)
	is_template = models.BooleanField(default=False)
	parent = models.ForeignKey('self',null=True,blank=True)

	pool = models.ForeignKey(Pool)
	version = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.name + " " + self.uuid.partition('-')[0]

class VolumeStatus(models.Model):
	allocation = models.IntegerField(default=0)

	volume = models.ForeignKey(Volume)
	timestamp = models.DateTimeField(auto_now=True)
	class Meta:
		get_latest_by = 'timestamp'

class VolumeLink(models.Model):
	volume = models.ForeignKey(Volume)
	star = models.ForeignKey(Star)


#### TODO: add version information

honcheonui/universe/views.py
# Create your views here.

from universe.models import *

from django.http import HttpResponse
import csv

def star(request, uuid):
	s = Star.objects.get(uuid=uuid)

	if request.method == 'POST':
		s.hostname = request.POST.get('hostname', s.hostname)
		s.type = request.POST.get('type', s.type)
		s.model = request.POST.get('model', s.model)
		s.memory = request.POST.get('memory', s.memory)
		s.cpus = request.POST.get('cpus', s.cpus)
		s.mhz = request.POST.get('mhz', s.mhz)
		s.save()

	# finally, return current values (GET and POST)
	return_str = "%s,%s,%s,%s,%s,%s" % \
			(s.uuid, s.type, s.model, s.memory, s.cpus, s.mhz)

	response = HttpResponse(status=200, content=return_str)
	response['X-Honcheonui-Result'] = "OK"
	response['X-Honcheonui-Method'] = request.method
	response['Pragma'] = 'no-cache'

	return response

def stars(request):
	ss = Star.objects.all()

	response = HttpResponse(mimetype='text/csv')
	response['Content-Disposition'] = 'attachment; filename=stars.csv'

	writer = csv.writer(response)
	for s in ss:
		writer.writerow([s.uuid,s.uri,s.name,s.constellation])

	return response

def pool(request, uuid):
	try:
		p = Pool.objects.get(uuid=uuid)
	except:
		# create new pool with args
		p = Pool(uuid=uuid,name=name,capacity=capacity)

	return_str = "%s,%s,%s,%s" % \
			(p.name, p.type, p.path, p.capacity)

	response = HttpResponse(status=200, content=return_str)
	response['X-Honcheonui-Result'] = "OK"
	response['X-Honcheonui-Method'] = request.method
	response['Pragma'] = 'no-cache'

	return response

honcheonui/universe/templates/universe/constellation_list.html
{% extends "base.html" %}

{% block title %}Service Instance{% endblock %}

{% block style %}{% endblock %}

{% block content %}


<div class="wgt_ds">
	<h2>Universe Overview</h2>
	<div class="action" id="service_action">
		<a href="create/">(Create Service)</a>
		<a href="/serviceitems/">New Service</a>
	</div>

	<style>
		.wgt_tree_frame { color: #bbb; }
		/*
		.wgt_tree_frame { border: 1px dotted white; }
		.wgt_tree_constellation { border-left: 1px dotted #555; }
		.wgt_tree_star { border-left: 1px dotted #555; }
		.wgt_tree_light { border-left: 1px dotted #555; }
		.wgt_tree_pool { border-left: 1px dotted #555; }
		.wgt_tree_volume { border-left: 1px dotted #555; }
		.wgt_item_constellation { border-top: 1px dotted #999; }
		.wgt_item_star { border-top: 1px dotted #999; }
		.wgt_item_light { border-top: 1px dotted #999; }
		.wgt_item_pool { border-top: 1px dotted #999; }
		.wgt_item_volume { border-top: 1px dotted #999; }
		*/
		.icon_constellation, .icon_star, .icon_light, .icon_pool, .icon_volume {
			display: inline;
		}
		.wgt_tree_star, .wgt_tree_light, .wgt_tree_pool, .wgt_tree_volume {
			margin-left: 16px;
			padding-bottom: 10px;
		}
		.box_25 { display: inline-block; width: 25em; }
		.box_15 { display: inline-block; width: 15em; }
		.box_10 { display: inline-block; width: 10em; }
		.box_5 { display: inline-block; width: 5em; }
		.box_3 { display: inline-block; width: 3em; }
		.box_2 { display: inline-block; width: 2em; }
		.box_1 { display: inline-block; width: 1em; }
		.box_25, .box_15, .box_10, .box_5, .box_3, .box_2 {
			border-bottom: 1px dotted #bbb;
		}
	</style>


	<div class="wgt_tree_frame">
		<div class="wgt_tree_constellation">
			{% for constellation in object_list %}
			<div class="wgt_item_constellation">
				<div class="icon_constellation">
					<img src="c" alt="c" width=10>
				</div>
				<div class='box_5'>{{ constellation.name }}</div>
				<div class='box_5'>{{ constellation.location }}</div>
				<div class='box_25'>{{ constellation.description }}</div>
				<div class='box_5' title='{{ constellation.uuid }}'
					>{{ constellation.uuid|make_list|slice:":5"|join:"" }}...</div>
				<div class='box_15'>{{ constellation.timestamp|date:"Y-m-d H:i:s" }}</div>
				<div class='box_5'>{{ constellation.star_set.count }} star(s)</div>
			</div>
			<div class="wgt_tree_star">
				{% for star in constellation.star_set.all %}
				<div class="wgt_item_star">
					<div class="icon_star">
						<img src="s" alt="s" width=10>
					</div>
					<div class='box_10'>{{ star.name }}</div>
					<div class='box_5' title='{{ star.uuid }}'
						>{{ star.uuid|make_list|slice:":5"|join:"" }}...</div>
					<div class='box_25'>{{ star.uri }}</div>
					<div class='box_5 tar'>{{ star.memory }}GB</div>
					<div class='box_5 tar'>{{ star.cpus }}core(s)</div>
					<div class='box_5 tar'>{{ star.mhz }}MHz</div>
					<!-- {{ star.hostname }} -->
					<div class='box_3'>{{ star.type }}</div>
					<div class='box_3'>{{ star.model }}</div>
				</div>
				{% endfor %}
			</div>
			<div class="wgt_tree_light">
				{% for light in constellation.light_set.all %}
				<div class="wgt_item_light">
					<div class="icon_light">
						<img src="l" alt="l" width=10>
					</div>
					<div class='box_10' title='xx'>{{ light.name }}</div>
					<div class='box_5' title='{{ light.uuid }}'
						>{{ light.uuid|make_list|slice:":5"|join:"" }}...</div>
					<div class='box_5'>{{ light.type }}</div>
					<div class='box_10 tar'>{{ light.memory }}KB</div>
					<div class='box_5 tar'>{{ light.cpus }}cpu(s)</div>
					<div class='box_5 tar'>{{ light.lightstatus_set.latest.cputime }}</div>
					<div class='box_5'>{{ light.lightstatus_set.latest.get_state_display }}</div>
					<div class='box_10'>{{ light.lightstatus_set.latest.star }}</div>
				</div>
				{% endfor %}
			</div>
			<div class="wgt_tree_pool">
				{% for pool in constellation.pool_set.all %}
				<div class="wgt_item_pool">
					<div class="icon_pool">
						<img src="p" alt="p" width=10>
					</div>
					<div class='box_10'>{{ pool.name }}</div>
					<div class='box_5' title='{{ pool.uuid }}'
						>{{ pool.uuid|make_list|slice:":5"|join:"" }}...</div>
					<div class='box_5'>{{ pool.get_type_display }}</div>
					<div class='box_5 tar'>{{ pool.poolstatus_set.latest.allocation }} /</div>
					<div class='box_5 tar'>{{ pool.capacity }}MB</div>
					<div class='box_5 tar'>{{ pool.poolstatus_set.latest.available }}MB</div>
					<div class='box_5'>{{ pool.poolstatus_set.latest.get_state_display }}</div>
					<div class='box_10'>{{ pool.poollink_set.get.star }}</div>
				</div>
				<div class="wgt_tree_volume">
					{% for volume in pool.volume_set.all %}
					<div class="wgt_item_volume">
						<div class="icon_volume">
							<img src="v" alt="v" width=10>
						</div>
						<div class='box_10'>{{ volume.name }}</div>
						<div class='box_5' title='{{ volume.uuid }}'
							>{{ volume.uuid|make_list|slice:":5"|join:"" }}...</div>
						<div class='box_5'>{{ volume.get_type_display }}</div>

						<div class='box_2'>{{ volume.is_template|yesno }}</div>
						<div class='box_2 tar'>{{ volume.serviceitem_set.count }}</div>
						<div class='box_10'>{{ volume.light }}</div>
						<div class='box_10'>{{ volume.parent }}</div>

						<!-- {{ volume.path }} -->
						<div class='box_5 tar'>{{ volume.volumestatus_set.latest.allocation }} /</div>
						<div class='box_5 tar'>{{ volume.capacity }}MB</div>
					</div>
					{% endfor %}
				</div>
				{% endfor %}
			</div>
			{% endfor %}
		</div>
	</div>

</div>

{% endblock %}

honcheonui/universe/templates/universe/template_list.html
<div>
{% if templates %}
	{% for t in templates %}
		<div>{{ t }}</div>
	{% endfor %}
{% else %}
{% endif %}
</div>